import { Routes } from '@angular/router';
import { DashboardComponent } from 'app/pages/dashboard/dashboard.component';
import { ViolationReviewComponent } from 'app/pages/violation-review/violation-review.component';
import { UserComponent } from 'app/pages/user/user.component';
import { BrandsComponent } from 'app/pages/brands/brands.component';
import { CampaignsComponent } from 'app/pages/campaigns/campaigns.component';
import { CouponsComponent } from 'app/pages/coupons/coupons.component';
import { AddPollComponent } from 'app/pages/add-poll/add-poll.component';
import { PollsComponent } from 'app/pages/polls/polls.component';
import { LuckyDrawComponent } from 'app/pages/lucky-draw/lucky-draw.component';
import { LuckyDrawViewComponent } from 'app/pages/lucky-draw-view/lucky-draw-view.component';
import { CampaignViewComponent } from 'app/pages/campaign-view/campaign-view.component';
import { CampaignCreateComponent } from 'app/pages/campaign-create/campaign-create.component';
import { BrandViewComponent } from 'app/pages/brand-view/brand-view.component';
import { BrandCreateComponent } from 'app/pages/brand-create/brand-create.component';
import { MerchantsComponent } from 'app/pages/merchants/merchants.component';
import { MerchantViewComponent } from 'app/pages/merchant-view/merchant-view.component';
import { MerchantCreateComponent } from 'app/pages/merchant-create/merchant-create.component';
import { UserViewComponent } from 'app/pages/user-view/user-view.component';
export const AdminLayoutRoutes: Routes = [
    { path: 'dashboard', component: DashboardComponent },
    { path: 'violation-review/:code', component: ViolationReviewComponent },
    { path: 'user', component: UserComponent },
    { path: 'brands', component: BrandsComponent },
    { path: 'campaigns', component: CampaignsComponent },
    { path: 'coupons', component: CouponsComponent },
    { path: 'polls', component: PollsComponent },
    { path: 'add-poll', component: AddPollComponent },
    { path: 'lucky-draw', component: LuckyDrawComponent },
    { path: 'lucky-draw-view', component: LuckyDrawViewComponent },
    { path: 'campaign-view', component: CampaignViewComponent },
    { path: 'campaign-create', component: CampaignCreateComponent },
    { path: 'brand-view', component: BrandViewComponent },
    { path: 'brand-create', component: BrandCreateComponent },
    { path: 'merchants', component: MerchantsComponent },
    { path: 'merchant-view', component: MerchantViewComponent },
    { path: 'merchant-create', component: MerchantCreateComponent },
    { path: 'user-view', component: UserViewComponent },
];
